# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.autostart", false);
user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1459139976);
user_pref("app.update.lastUpdateTime.background-update-timer", 1428569128);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1459140096);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1459163046);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1459139856);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1459148526);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.display.use_document_fonts", 0);
user_pref("browser.download.dir", "/media/maple/Maple's_Workspace/tianyu");
user_pref("browser.download.folderList", 2);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/media/maple/Maple's_Workspace/file_storage/linux配置，基本技巧/Debian下的一些有用配置/linux翻墙成功goagent+chrome");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.save_converter_index", 1);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.link.open_newwindow.restriction", 0);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.restore_on_demand", false);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20151103235259");
user_pref("browser.slowStartup.averageTime", 10832);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage", "www.baidu.com");
user_pref("browser.startup.homepage_override.buildID", "20150320202338");
user_pref("browser.startup.homepage_override.mstone", "36.0.4");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0,\"addons\":2,\"bookmarks\":0}");
user_pref("browser.tabs.animate", false);
user_pref("browser.tabs.warnOnOpen", false);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"nav-bar\":[\"history-panelmenu\",\"urlbar-container\",\"youtubeflashvideoplayer-toolbarbutton\",\"fnvfox_toolbarButton\",\"foxyproxy-toolbar-icon\",\"webrtc-status-button\",\"gd12gtbutton\",\"toggle-button--helper-sigsavefromnet-sf-menu_button\",\"loop-button\",\"abp-toolbarbutton\",\"personal-bookmarks\",\"dta-button\",\"customizableui-special-spacer3\",\"downloads-button\",\"customizableui-special-spacer2\",\"aup-toolbarbutton\",\"action-button--youtubeunblockerunblockeryt-youtube-unblocker\",\"action-button--jid1-hav2inxanqpieajetpack-youtube-flash-player-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-butto